Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = [-1, 0, 1, 2,  3, 4, 5]
y = [-2.52,  0.85,   3.21,  7.19,  8.93, 12.89, 15.40]

plt.figure()
plt.scatter(x,y)
plt.xlabel('Ursache')
plt.ylabel('Wirkung')
plt.title('KÃ¼nstliche Messdaten mit linearem Zusammenhang');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      1[0m x [38;5;241m=[39m [[38;5;241m-[39m[38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m,  [38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m5[39m]
[1;32m      2[0m y [38;5;241m=[39m [[38;5;241m-[39m[38;5;241m2.52[39m,  [38;5;241m0.85[39m,   [38;5;241m3.21[39m,  [38;5;241m7.19[39m,  [38;5;241m8.93[39m, [38;5;241m12.89[39m, [38;5;241m15.40[39m]
[0;32m----> 4[0m [43mplt[49m[38;5;241m.[39mfigure()
[1;32m      5[0m plt[38;5;241m.[39mscatter(x,y)
[1;32m      6[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mUrsache[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

