Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/turtle/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# blaue y-Koordinaten = Messpunkte
y_blau = co2

# Berechnung der roten y-Koordinaten, indem wir x-Koordinaten der Messpunkte
# in die Modellfunktion y = m*x + b einsetzen
x = jahre
y_rot = 0.0344 * x - 64.7516

# Berechnung Gesamtfehler
N = 29
gesamtfehler = 1/N * np.sum( (y_blau - y_rot)**2 )

print(f'Der Gesamtfehler ist {gesamtfehler}.')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 11[0m
[1;32m      9[0m [38;5;66;03m# Berechnung Gesamtfehler[39;00m
[1;32m     10[0m N [38;5;241m=[39m [38;5;241m29[39m
[0;32m---> 11[0m gesamtfehler [38;5;241m=[39m [38;5;241m1[39m[38;5;241m/[39mN [38;5;241m*[39m [43mnp[49m[38;5;241m.[39msum( (y_blau [38;5;241m-[39m y_rot)[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m )
[1;32m     13[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mDer Gesamtfehler ist [39m[38;5;132;01m{[39;00mgesamtfehler[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

